explorer "E:\personal\maestria\tesis\Jeronimo\trunk\documents\thesis\bibliografia\listado_inicial\Botsch2010\Polygon Mesh Processing Mario Botsch et.al 2010.pdf"
explorer "E:\personal\maestria\tesis\Jeronimo\trunk\documents\thesis\bibliografia\listado_inicial\Taubin2000\taubin-iccv95b.pdf"
explorer "E:\personal\maestria\tesis\Jeronimo\trunk\documents\thesis\bibliografia\listado_inicial\Taubin2000\Taubin-sg95.pdf"
explorer "E:\personal\maestria\tesis\Jeronimo\trunk\documents\thesis\bibliografia\listado_inicial\Taubin2000\Taubin-star-eg00.pdf"
explorer "E:\personal\maestria\tesis\Jeronimo\trunk\documents\thesis\bibliografia\listado_inicial\Levy2010\a8-levy.pdf"
explorer "E:\personal\maestria\tesis\Jeronimo\trunk\documents\thesis\bibliografia\listado_inicial\Zhang2010\Zhang_et_al-2010-Computer_Graphics_Forum.pdf"
explorer "E:\personal\maestria\tesis\Jeronimo\trunk\documents\thesis\TQLBO-paper\papers\Herholz2012\Diplomarbeit_Herholz_201301.pdf"
explorer "E:\personal\maestria\tesis\Jeronimo\trunk\documents\thesis\TQLBO-paper\papers\Xiong2011\2011_Mean Laplace-Beltrami.pdf"
explorer "E:\personal\maestria\tesis\Jeronimo\trunk\documents\thesis\TQLBO-paper\papers\Desbrun1999\ImplicitFairing.pdf"